In [2]:
import os
import traceback

dir = "/Users/user/Desktop/hooklog"

def gothrougheveryfile(dir):  # go through every csv and concat to one csv this part has move to concatallcsv
    i = 0
    filenamelist = list()
    for subdir in os.listdir(dir):# outside each folder
        if subdir[0] == '.':
            continue
        for filename in os.listdir(dir+"//"+subdir):
            if filename[0] == '.':
                continue
            wholefilepath = dir + "//"+ subdir +"//" +filename
            filenamelist.append(wholefilepath)
    return filenamelist

filepathlist = gothrougheveryfile(dir)


In [27]:
def argumentset(filepathlist):
    listarg = []
    for z in range(len(filepathlist)): # z indicate which text

        with open(filepathlist[z]) as f:
            content = f.readlines()
        # you may also want to remove whitespace characters like `\n` at the end of each line
        content = [x.strip() for x in content]

        for i in range(len(content)):
            if content[i].find("=")!=-1:
                #print(content[i])
                #print(content[i].find("="))
                u = content[i].find("=")
                #print(content[i][u+1:])
                listarg.append(content[i][u+1:])

    listarg = set(listarg)

    listarg = list(listarg)
    #print(listarg)


    return listarg


In [28]:
def apiset(filepathlist):
    k = 0
    j = 0
    listapi = []
    for z in range(len(filepathlist)):

        #print(pathlist[j])


        with open(filepathlist[z]) as f:
            content = f.readlines()
        # you may also want to remove whitespace characters like `\n` at the end of each line
        content = [x.strip() for x in content]
        encountertimestamp = False
        for i in range(len(content)):
            if encountertimestamp == True:
                #print(content[i])  # there will be apis
                #print(i)
                listapi.append(content[i])
                encountertimestamp = False
                k = k+1

            #print(i)

            try:

                if content[i] != "":
                    if content[i][0] == '#':
                        encountertimestamp = True

                        j =j+1
            except :
                print("error"+str(i))
                print(len(content))
                print(content[i])
                traceback.print_exc()


        content =[]


    print(j)
    print(k)

    listapi = set(listapi)
    
    listapi = list(listapi)

    #print(listapi)

    print(j)
    print(k)

    return listapi

In [29]:
apisetlist = apiset(filepathlist)
argumentsetlist = argumentset(filepathlist)

575323
575323
575323
575323


In [6]:
fname = r"/Users/user/Desktop/hooklog/Bdmj/0e5d047639d4fa1284e222c534bb3998aebb0654d5464f39180c7ec3fdf3baff_3276.trace.hooklog"
with open(fname) as f:
    content = f.readlines()
# you may also want to remove whitespace characters like `\n` at the end of each line
content = [x.strip() for x in content]

In [7]:
print(content)

['3276 malware.exe', '#277500000', 'LoadLibrary', 'lpFileName=C:\\WINDOWS\\system32\\IMM32.DLL', 'Return=76390000', '#277920000', 'LoadLibrary', 'lpFileName=LPK.DLL', 'Return=629c0000', '#278240000', 'LoadLibrary', 'lpFileName=gdi32.dll', 'Return=77f10000', '#278650000', 'RegQueryValue', 'hKey=HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\CriticalSectionTimeout', 'Return=0', '#278650001', 'RegQueryValue', 'hKey=HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Ole\\RWLockResourceTimeOut', 'Return=2', '#280870000', 'LoadLibrary', 'lpFileName=KERNEL32.DLL', 'Return=7c800000', '#280900000', 'LoadLibrary', 'lpFileName=ADVAPI32.dll', 'Return=77dd0000', '#280940000', 'LoadLibrary', 'lpFileName=ntdll.dll', 'Return=7c900000', '#280950000', 'LoadLibrary', 'lpFileName=ole32.dll', 'Return=774e0000', '#280970000', 'LoadLibrary', 'lpFileName=USER32.dll', 'Return=7e410000', '#280990000', 'LoadLibrary', 'lpFileName=WINHTTP.dll', 'Return=4d4f0000', '#281010000', 'CreateFile', 'hName=

In [22]:
import numpy as np 

allapiandarglist=[]
apiinfolist= []
encounterapi = False
for i in range(len(content)):   
    if content[i][0] =="#" : # start to catch one api info
        if len(apiinfolist) !=0:
            allapiandarglist.append(apiinfolist) # when encounter timestamp means go to another api
        apiinfolist= [] #reinit everytime when encounter a timestamp
        encounterapi = True
    if encounterapi == True:
        if content[i][0] !="#":
                if content[i].find("=")!=-1:
                    u = content[i].find("=")  
                    apiinfolist.append(content[i][u+1:])
                    
                else:    
                    apiinfolist.append(content[i])

allapi=np.array([np.array(x) for x in allapiandarglist]) #  convert two dim list to two dim array
#allapi = np.array(allapiandarglist)
               
print(allapi)

    
                   

[array(['LoadLibrary', 'C:\\WINDOWS\\system32\\IMM32.DLL', '76390000'],
      dtype='|S29')
 array(['LoadLibrary', 'LPK.DLL', '629c0000'], dtype='|S11')
 array(['LoadLibrary', 'gdi32.dll', '77f10000'], dtype='|S11')
 array(['RegQueryValue',
       'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\CriticalSectionTimeout',
       '0'], dtype='|S90')
 array(['RegQueryValue',
       'HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Ole\\RWLockResourceTimeOut',
       '2'], dtype='|S63')
 array(['LoadLibrary', 'KERNEL32.DLL', '7c800000'], dtype='|S12')
 array(['LoadLibrary', 'ADVAPI32.dll', '77dd0000'], dtype='|S12')
 array(['LoadLibrary', 'ntdll.dll', '7c900000'], dtype='|S11')
 array(['LoadLibrary', 'ole32.dll', '774e0000'], dtype='|S11')
 array(['LoadLibrary', 'USER32.dll', '7e410000'], dtype='|S11')
 array(['LoadLibrary', 'WINHTTP.dll', '4d4f0000'], dtype='|S11')
 array(['CreateFile',
       'C:\\Documents and Settings\\All Users\\Desktop\\malware.exe',
       'GENERIC_R

In [23]:
print(allapiandarglist)

[['LoadLibrary', 'C:\\WINDOWS\\system32\\IMM32.DLL', '76390000'], ['LoadLibrary', 'LPK.DLL', '629c0000'], ['LoadLibrary', 'gdi32.dll', '77f10000'], ['RegQueryValue', 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\CriticalSectionTimeout', '0'], ['RegQueryValue', 'HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Ole\\RWLockResourceTimeOut', '2'], ['LoadLibrary', 'KERNEL32.DLL', '7c800000'], ['LoadLibrary', 'ADVAPI32.dll', '77dd0000'], ['LoadLibrary', 'ntdll.dll', '7c900000'], ['LoadLibrary', 'ole32.dll', '774e0000'], ['LoadLibrary', 'USER32.dll', '7e410000'], ['LoadLibrary', 'WINHTTP.dll', '4d4f0000'], ['CreateFile', 'C:\\Documents and Settings\\All Users\\Desktop\\malware.exe', 'GENERIC_READ', 'OPEN_EXISTING', '40'], ['RegQueryValue', 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Cryptography\\Defaults\\Provider Types\\Type 001\\Name', '0'], ['RegQueryValue', 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Cryptography\\Defaults\\Provider Types\\Type 001\\Name', '0'], ['RegQuer

In [40]:
listallapiintegerencode = [] # one hooklog's apis integer encoding
listoneapiandargcode = [] # for one api to be a list of integer inorder to onehot encoding
for i in range(len(allapiandarglist)): # i is index for apis
    for j in range(len(allapiandarglist[i])): # j is index in one apis means apiname or its arg
        allapiandarglist[i][j]
        if j == 0: # index 0 is always apiname
            indexapiname = apisetlist.index(allapiandarglist[i][j])
            listoneapiandargcode.append(indexapiname)
        else: 
            indexarg = argumentsetlist.index(allapiandarglist[i][j])
            listoneapiandargcode.append(indexarg)
    listallapiintegerencode.append(listoneapiandargcode) # when one api encoded append its list to big list which included all apis
    listoneapiandargcode=[]

print(listallapiintegerencode)

[[17, 1676, 5008], [17, 94, 5168], [17, 5992, 1065], [0, 1951, 5173], [0, 9182, 812], [17, 7328, 8124], [17, 103, 5659], [17, 2872, 8170], [17, 4160, 6586], [17, 5350, 2193], [17, 2525, 4771], [20, 9123, 7383, 5503, 6892], [0, 5822, 5173], [0, 5822, 5173], [0, 872, 5173], [0, 7478, 5173], [0, 7478, 5173], [20, 4585, 7383, 5503, 6891], [20, 4585, 7383, 5503, 6891], [20, 345, 7383, 5503, 6889], [20, 4585, 7383, 5503, 6891], [20, 4585, 7383, 5503, 6891], [20, 4585, 7383, 5503, 6891]]


In [31]:
print(apisetlist[17])

LoadLibrary


In [33]:
print(argumentsetlist[1676])

C:\WINDOWS\system32\IMM32.DLL


In [39]:
print(argumentsetlist[1951])

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\CriticalSectionTimeout


In [37]:
print(apisetlist[0])

RegQueryValue


In [58]:
onehot = []
onehotallapis =[]

for i in range(len(listallapiintegerencode)): # for one api in one hooklog 
    oneapi_onehotforapi= [0]* len(apisetlist)
    oneapi_onehotforarg= [0]* len(argumentsetlist)
    for j in range(len(listallapiintegerencode[i])): # in one api
               if j == 0: # time to encode api
                   oneapi_onehotforapi[listallapiintegerencode[i][j]] = 1
               else: # time to encode arg
                   oneapi_onehotforarg[listallapiintegerencode[i][j]] = 1
    
    onehot = oneapi_onehotforapi + oneapi_onehotforarg # onehot for one api
    onehotallapis.append(onehot)
    onehot = []

print(onehotallapis[2][18])
    
    
     

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [50]:
# list to nparray
#integer_encoded=np.array([np.array(x) for x in listallapiintegerencode])

#print(integer_encoded.shape)

#print(integer_encoded)


(23,)
[array([  17, 1676, 5008]) array([  17,   94, 5168])
 array([  17, 5992, 1065]) array([   0, 1951, 5173])
 array([   0, 9182,  812]) array([  17, 7328, 8124])
 array([  17,  103, 5659]) array([  17, 2872, 8170])
 array([  17, 4160, 6586]) array([  17, 5350, 2193])
 array([  17, 2525, 4771]) array([  20, 9123, 7383, 5503, 6892])
 array([   0, 5822, 5173]) array([   0, 5822, 5173])
 array([   0,  872, 5173]) array([   0, 7478, 5173])
 array([   0, 7478, 5173]) array([  20, 4585, 7383, 5503, 6891])
 array([  20, 4585, 7383, 5503, 6891])
 array([  20,  345, 7383, 5503, 6889])
 array([  20, 4585, 7383, 5503, 6891])
 array([  20, 4585, 7383, 5503, 6891])
 array([  20, 4585, 7383, 5503, 6891])]


In [69]:
print(onehotallapis[2][1065+len(apisetlist)])
    

1


In [70]:
print(onehotallapis)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [71]:
print(onehotallapis.shape)

AttributeError: 'list' object has no attribute 'shape'

In [72]:
onhotencode =np.array([np.array(x) for x in onehotallapis]) # nparray onehot encode for one hooklog

In [74]:
onhotencode.shape

(23, 9252)

In [79]:
from pandas import read_csv
from pandas import DataFrame
df = DataFrame(onhotencode)
df.to_csv("test.csv")

In [80]:
def gothrougheveryfile(dir):  # go through every csv and concat to one csv this part has move to concatallcsv
    i = 0
    filenamelist = list()
    for subdir in os.listdir(dir):# outside each folder
        if subdir[0] == '.':
            continue
        for filename in os.listdir(dir+"//"+subdir):
            if filename[0] == '.':
                continue
            wholefilepath = dir + "//"+ subdir +"//" +filename
            filenamelist.append(wholefilepath)
    return filenamelist

In [81]:
dir = "/Users/user/Desktop/hooklog"
filepathlist = gothrougheveryfile(dir)

for filepath in filepathlist:
    

['/Users/user/Desktop/hooklog//Bdmj//0e5d047639d4fa1284e222c534bb3998aebb0654d5464f39180c7ec3fdf3baff_3276.trace.hooklog', '/Users/user/Desktop/hooklog//Bdmj//12b0658e6816188ac2094f817787204443db73392f01da74e6278e239cf0ca98_3212.trace.hooklog', '/Users/user/Desktop/hooklog//Bdmj//130114e0c6cfcd8d956f230dc97d582e2e3817d1d923eae4bf9538964d0f2cfa_3236.trace.hooklog', '/Users/user/Desktop/hooklog//Bdmj//14479c3c89eae8862f8b85592e39d4c05ef0772b0d7ce7b49448cb0179e0de7a_3160.trace.hooklog', '/Users/user/Desktop/hooklog//Bdmj//1628a8c1ba4e7a2e9634c4c7bcd20e95272bda2d6a0362e4d310a9606f00d3ff_3216.trace.hooklog', '/Users/user/Desktop/hooklog//Bdmj//1de954caef26e70d04290653a772a0c7b4d72bdb02e0c416752c3ab005d46329_3280.trace.hooklog', '/Users/user/Desktop/hooklog//Bdmj//1f34ea89f3b8345c1f6929604b0b4751abd29a7187b108b0204706b62a432956_3324.trace.hooklog', '/Users/user/Desktop/hooklog//Bdmj//3083f8ad8091386fec875a81098df39435202d9e1ce68f65be82a49a439dcf6a_3292.trace.hooklog', '/Users/user/Desktop/ho